### ISSUE TITLE
Exporting permissions on requried fields resets permissions

### ISSUE THREAD

**Issue by DenuxPlays** [pluginpal/strapi-plugin-config-sync#125] opened 2024-03-22 08:21 UTC
### Describe the bug

I have a required and auto-generated field.
I want that non-admin users cannot see, change or delete this field so I remove all the permissions from it.
Now when I export it the permissions gets resetted (not only on the import also on the export!)

### Steps to reproduce the behavior

1. create a required auto-generated field
2. remove the permissions from it for a role
3. export the settings
4. reload
5. see permissions reset

### Expected behavior

Export it and DO NOT CHANGE ANYTHING IN STRAPI it should only read configurations.

### Screenshots

///

### Code snippets

///

### System

- Node.js version:v20.11.0
- NPM version: v1.22.19 (yarn)
- Strapi version: v4.21.0
- Database: MariaDb 10.6
- Operating system: Debian-12
- Is your project Javascript or Typescript: Typescript

### Additional context

I already opened an issue on strapi because I am not sure where the issue occurs:
https://github.com/strapi/strapi/issues/19892

**Comment by boazpoolman** [comment] 2024-03-22 08:26
What do you mean exactly with "auto-generated"? Is this a `uid` type field, or a different type?

**Comment by DenuxPlays** [comment] 2024-03-22 08:38
> What do you mean exactly with "auto-generated"? Is this a `uid` type field, or a different type?

Yes
UID field and requried.
These are the settings that we use

**Comment by boazpoolman** [comment] 2024-03-22 08:49
Allright. Will have to try to reproduce, but it does sound more like a Strapi issue to me.
Especially if this only happends for the `uid ` fields. To the `config-sync` plugin they are not handled differently than any other field.

**Comment by boazpoolman** [comment] 2024-04-10 20:17
Seems, like a duplicate of https://github.com/strapi/strapi/issues/16890

@DenuxPlays can you confirm?

**Closed** 2024-04-11 06:40 UTC
Labels: bug, Needs investigation
